---
.travis.yml:
  secure_global_env:
    # PUBLISHER_PASSWORD
    - "Mj6wIfeI0gRkgAeeYP5qphoxmKmbjVWisw8FiKCygSj7iKnPdsYHVRu1I//Y\nhj2UMntig48dEh0h42hyBbLSamKOaGo79EYf+HX8HX8E0OYG3TsuWQvUH3YW\nsGBE4aCvpyiKDVrk1op0r+zxqLXyfFBNawA9nwHgUq+TMPoKfts="
